// tests for main_brute_force.dart

import 'main.dart';

// TESTS GENERATED BY ChatGPT-4
void main() {
  assert(getValue('two1nine') == 29);

  assert(getValue('eightwothree') == 83);

  assert(getValue('abcone2threexyz') == 13);

  assert(getValue('xtwone3four') == 24);

  assert(getValue('4nineeightseven2') == 42);

  assert(getValue('zoneight234') == 14);

  assert(getValue('7pqrstsixnine') == 79);

  assert(getValue('9cbncbxclbvkmfzdnldc') == 99);

  assert(getValue('jjn1drdffhs') == 11);

  assert(getValue('3six7') == 37);

  assert(getValue('38rgtnqqxtc') == 38);

  assert(getValue('rxszdkkv3j8kjhbm') == 38);

  assert(getValue('54nzzddht8ninelrkkseightseven6') == 56);

  assert(getValue('6fourmnvkgnthjtnjqkr') == 64);

  assert(getValue('nineninezsstmkone4sjnlbldcrj4eight') == 98);

  assert(getValue('3rdnfkvrx4twoqgeightqkgmn') == 38);

  assert(getValue('6mlhponeglrzrvbsseven') == 67);

  assert(getValue('five8spgxz8') == 58);

  assert(getValue('3three2dfourfour58') == 38);

  assert(getValue('9q') == 99);

  assert(getValue('two45') == 25);

  assert(getValue('five8mpkpdfiveeightfourseven') == 57);

  assert(getValue('93threefive3three92') == 92);

  assert(getValue('6jdzeightnineone1sclhzrnrjxfive') == 65);

  assert(getValue('6nseven16lbztpbbzthree8five') == 65);

  assert(getValue('eight6mntljvbfrmftsffchsix4') == 84);

  assert(getValue('4twosixvnhjl') == 46);

  assert(getValue('8d') == 88);

  assert(getValue('eightsevenvqvzlqxkbm6rqhsgqpnine7twonex') == 81);

  assert(getValue('seven96') == 76);

  assert(getValue('ck8tv6') == 86);

  assert(getValue('2mcddqpnbxssmrc6') == 26);

  assert(getValue('zsfbkrjjqpbbone6six2') == 12);

  assert(getValue('fourone8hfrkxrr') == 48);

  assert(getValue('7ninetphdpcx') == 79);

  assert(getValue('9gcn9six4mfnjgtcdc') == 94);

  assert(getValue('6onevsevenseven4three') == 63);

  assert(getValue('ldssggpknine7') == 97);

  assert(getValue('twolltbfkhltwo892jngx') == 22);

  assert(getValue('rsh1five3ninefourmfk') == 14);

  assert(getValue('xtrh534nqxr') == 54);

  assert(getValue('ggllvfjthreefcckbninekspmf6bnpkvt2') == 32);

  assert(getValue('kng16') == 16);

  assert(getValue('kqgthcleightsixeight96nine69') == 89);

  assert(getValue('nchcdqbsxmeighttwo65onevtqrznxmnl') == 81);

  assert(getValue('chphzzqb6threeqhspbgkrn6') == 66);

  assert(getValue('8threevbqxl4') == 84);

  assert(getValue('99eight2hgdvcqdqxsnmkxctskvxxvqxjt') == 92);

  assert(getValue('9qb95oneightsf') == 98);

  assert(getValue('tfmpcthbdbnzhldnbj96') == 96);

  assert(getValue('9qb95oneightsf') == 98);

  assert(getValue('cq57sixeightwosvx') == 52);

  assert(getValue('26sevenseven3twonelq') == 21);

  assert(getValue('4onesnfive1sixeightwof') == 42);

  assert(getValue('fcpkrvmtzxkrfsmqcbzeight7gfourfbkthreeoneightvm') == 88);

  assert(getValue('six31vtcphkpltgbcprdhvdfivefoureightwonvh') == 62);

  assert(getValue('rjnmxbflvn5oneightpj') == 58);

  assert(getValue('4xrlpc7c82oneightk') == 48);

  assert(getValue('dklfjdmzc15zchbgmbqkgzgkn1sixsixeightwovz') == 12);

  assert(getValue('twofiveoneseven1rqjvrrxtwonen') == 21);

  assert(getValue('86vbnpsixthreetwonevng') == 81);

  print('ALL TESTS PASSED!');
}
